### ISSUE TITLE
Error when trying to connect two PD nodes with AF edges

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#102]
When we try to connect two PD nodes with AF edges, it gives error in console.

**Comment by kinimesi** [comment]
@hasanbalci Right now since map type is not set on load, this is an expected error (I mentioned this in a comment [here](https://docs.google.com/document/d/1yv-CCseixG4Rr0CzbaJHtAexn5pBWcK1TzrzC1vvxNE/edit?usp=sharing)).

For now, before testing AF functionality, first create a new map from`File > New` menu.

**Comment by hasanbalci** [comment]
I think this problem is fixed after setting map types on load.
