### ISSUE TITLE
Dynamic infobox placement to be redone on layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#104]
Layout might / will often change dimensions of compound nodes, which in turn affect the placement of infoboxes. Currently, there is no update of these placement upon layout.

**Comment by kinimesi** [comment]
Also the placement of compartment infoboxes is not updated when the size of compartment is changed by moving its children. See the GIF below:
![bwb3wmu7er](https://user-images.githubusercontent.com/7281872/27881640-2133c8ca-61d2-11e7-88f5-cc985d825648.gif)

**Comment by royludo** [comment]
The particular problem pointed out by @kinimesi is fixed in 983ac6876347a39a3906823b2119f6c354a0ffed. But there are lots of things remaining that lead to the same problem.

For example, when resizing a child node and undo/redoing that, infobox are not updated. Maybe this can be solved by triggering resize events upon undoing/redoing resize, I'm not sure it's done right now.

Also, when there is more than one level of nested elements, moving or resizing the innermost elements won't trigger the update of the outermost element's infoboxes. I don't know how to solve that efficiently.

**Comment by ugurdogrusoz** [comment]
We ll have to do this case by case. As we discover other problems, we'll update infobox calculation in those situations as well
