### ISSUE TITLE
Node label font size issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#107]
When "Adjust Node Label Font Size Automatically" is set to true,
- complex labels are placed incorrectly (slightly below where they should be)
- when label size is set to Small or Large, certain node types' (compounds and phenotype) labels don't change

**Comment by kinimesi** [comment]
@ugurdogrusoz automatic label size calculation is done by using the height of nodes. Since compound nodes usually have large height values, using the same technique results in very large label sizes. In order to avoid this, right now a constant label size (16) is returned for compound nodes https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/element-utilities.js#L442

How should the label size of compound nodes be calculated?

Problem related to phenotype is solved after removing it from process list.

**Comment by ugurdogrusoz** [comment]
Since compound margins are constant, I guess it's ok that we return constant label size for them (ignore the request on changing it with size)

Let's just solve the problem with complex labels being off.

**Comment by ugurdogrusoz** [comment]
Sorry to be changing requirements here but I've done some further investigation and realized:
- by default simple node, complex and compartment font sizes are 11, 11, and 14
So, when font sizes are to be determined automatically, I think we should keep what we're doing for simple nodes, and for compounds we should do the following:
- Complexes: S:10, R: 11 (same as default), L:12
- Compartments: S: 12, R: 14 (same as default), L: 16
