### ISSUE TITLE
Weird layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#143]
Puzzling weird layout on this model in Newt:
[polyq_proteins_interference.xml.txt](https://github.com/iVis-at-Bilkent/newt/files/1168091/polyq_proteins_interference.xml.txt)

**Comment by hasanbalci** [comment]
I think this is a behavior sourced from current layout force model. Since compound nodes are not effected from repulsion force when they are interacting with simple nodes, it causes this weird layout. 

This will be solved when we move on to the updated force model where compounds will be effected from repulsion forces based on their weights (# of children).

**Comment by hasanbalci** [comment]
I think, the new force model https://github.com/cytoscape/cytoscape.js-cose-bilkent/commit/132e236d28fa51cbd72b4566687f940592aed871 solved this issue.
