### ISSUE TITLE
Error on loading model with custom annotation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#178]
We get:
(anonymous) @ bundle.js:1869
bundle.js:3133 TypeError: Cannot read property 'getAllIds' of null
    at Object.handleAnnotations (bundle.js:3180)
    at Object.addCytoscapeJsNode (bundle.js:3179)
    at Object.traverseNodes (bundle.js:3181)
    at Object.convert (bundle.js:3188)
    at bundle.js:3132
bundle.js:251

**Comment by royludo** [comment]
The annotations aren't saved in sbgnml.` <annotation/>` element is there but empty. I'll look into that.

**Comment by royludo** [comment]
@ugurdogrusoz that comes from libsbgn.js. It will be fixed tomorrow.

**Comment by royludo** [comment]
@ugurdogrusoz @kinimesi this is fixed in libsbgn.js@0.1.3, it's published and I tested it locally. This being said, I saw some new package-lock.json file in sbgnviz and I'm not 100% how it works, and the unstable branch is quite behind the master branch. I'm not sure what to do at all here, what to update, so I'll let you guys update things on your part.
