### ISSUE TITLE
Multiple tab UI improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#211]
I think multiple tab UI would improve if we did the following:
- Use map name (Map Properties > Name) for tab title (truncate when needed using ...) Use the text "Pathway #0", "Pathway #1", etc. by default, and when one changes, change the other one. 
- Reverse the tab shape (rounded corners of the rectangle should be at the bottom, not at the top since we want the tab to look like part of the canvas). We might want to increase rounding to make this more obvious as well.
- Change the background color of the tab shapes (active -> white: same as canvas, inactive -> gray: same as bottom bar, see below)
- Paint the background of the bar where the tabs are displayed (the entire bottom tab) gray [see (2) in the figure below]
- Start tabs at the same x location where the canvas starts [see (1) in the figure below]
![tab-ui-improvements](https://user-images.githubusercontent.com/3874988/33704772-d4cf2c4a-db3e-11e7-8df4-9cf721f54ce4.png)

**Comment by metincansiper** [comment]
@ugurdogrusoz I made the requested changes.

**Comment by ugurdogrusoz** [comment]
Thanks @metincansiper. A couple of minor improvements:

![image](https://user-images.githubusercontent.com/3874988/33818545-9eedcfda-de56-11e7-9b79-b95341f82cf8.png)

1) Since the space below the tab bar is white, the tabs still don't look like they belong to the canvas. Can we perhaps draw a line between the gray of the tabs and the white background (marked with 1 above) below it? 

2) To help tabs look part of the canvas, we could get rid of the gray line (border of the tabs' background) between the canvas and the tabs, marked with 2 above.

3) Increase the rounding of the bottom of the active tab (do the same with inspector tabs for consistency).

So, we would like something like one of this:
![image](https://user-images.githubusercontent.com/3874988/33818898-91b30bf8-de58-11e7-957e-a8ddb3c6d895.png)

If this doesn't work or is not possible, we could perhaps go with something like this:
![image](https://user-images.githubusercontent.com/3874988/33818818-18456bf8-de58-11e7-8929-ed9a1b23b324.png)

**Comment by metincansiper** [comment]
@ugurdogrusoz I made some experiments on this. I am able to do it like shown by the following figure.

<img width="149" alt="screen shot 2017-12-11 at 4 24 30 pm" src="https://user-images.githubusercontent.com/6534865/33860952-024baea6-de90-11e7-8fc2-3d3527964edd.png">

I am not able to totally remove the grey line that is rendered on the area marked by 2 because I think that the remaining line there is not caused by the tab itself, it is just the borders of the container of the canvas.

Also, I realized that after making that experimental changes for some screen sizes (pretty rare cases) it looks like as you show by the following figure.
<img width="181" alt="screen shot 2017-12-11 at 5 02 46 pm" src="https://user-images.githubusercontent.com/6534865/33861958-37e14daa-de95-11e7-8b8d-2e81f5b4c112.png">

 I mean that the line at the area marked by 2 becomes invisible. However, I think that it is an unexpected behaviour. For that screen sizes tabs seems to be rendered a bit above the expected location and so they hides the thin borders of the canvas container. I am not able to figure out why that happens.

**Comment by ugurdogrusoz** [comment]
I think what you have in that figure is just fine, let's do that.
One minor thing I just noticed is that upon creation of a new tab, tab title is "Pathway #X" but the pathway name under General Properties is not set accordingly.

**Comment by metincansiper** [comment]
It is because of that I am setting tab title as the map name if it exists and "Pathway #X" if it does not exist. How should it be? Should the tab title alway be the same as the map name and map name should be "Pathway #X" by default?

**Comment by ugurdogrusoz** [comment]
I think setting default map name as Pathway #X when a new map is created should solve our problem. We would like the 2 to be consistenly the same.

**Comment by metincansiper** [comment]
@ugurdogrusoz I implemented the requested improvements.
