### ISSUE TITLE
Overriding options for launch by URL/URI

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#231]
The users should be able to specify / override map properties on launch by URL and URI. For instance:
  http://web.newteditor.org/?URI=http://identifiers.org/reactome/R-HSA-6803211&enablePorts=false

The naming should be consistent with the API naming and should cover all map properties (those per map options that can be saved in .sbgnml files).

**Comment by metincansiper** [comment]
@ugurdogrusoz I think that there are 2 ways of doing this.
Currently parameters are read from URI/URL by name. I think that since now we would need to retrieve more then 2 parameters (URL and URI) we can change this and get a map of name-value pairs that covers all parameters.

After that one way would be assuming that all of the properties of the object (other then URI or URL) are mapProperties and merging them directly to the mapProperties that comes from the content of the file.

The other way would be considering that there could be other parameters except map properties and URI/URL and so before performing merge checking if the parameters are map properties. In this way we will need to keep a set of possible map properties in either sbgnviz level or both of sample applications (If all of the possible map properties are ensured to be same for both of applications defining the set in sbgnviz would make more sense but otherwise we should define it for the apps seperately). 

In the second way we will need to update the set of possible map properties when a new map property added or removed but I think that it is safer.

Which way looks better?

**Comment by ugurdogrusoz** [comment]
I am not sure I fully understand but yes there might be other options (options other than map properties) that we want to pass on to URI/URL reader in the future. As long as we can do this, we should be fine. What do you think @kinimesi, @ahmetcandiroglu ?

**Comment by ahmetcandiroglu** [comment]
I think second way would be better since it is safer

**Comment by metincansiper** [comment]
I also think that the second way would be better especially considering that there could be other parameters in URL. I am implementing in that way.

@ugurdogrusoz  I have one more question. In current implementation parameters were ignoring case I mean specifying the ```url``` parameter as any of "URL , "url", "uRI" was possible. I cannot keep this behaviour if I go through the url only once to save the each parameter to an object instead of getting each of them by name separately. For uri and url parameters I can check both of whole lower cases or whole capitals but the other parameters will become case sensitive. 

Is it fine? If not I will need to call getParameterByName for any possible parameter name and I afraid it would not be an effective way.

**Comment by metincansiper** [comment]
For my last question, getting the parameter in a case insensitive way would still be possible but it will require an extra dirty stuff, I think even getting whole parameters separately by their name would be more preferable. Also, case insensitivity would not be ideal for map related parameters because they will be matching the ```mapProperties``` that comes from file. Therefore, I would like to avoid case insensitivity for map related parameters if you think that it is okey. For url and uri parameters I can keep having case insensitivity if it is needed.

**Comment by ugurdogrusoz** [comment]
if you can keep URL/URI parameters case insensitive, it's OK to have map properties case sensitive

**Comment by metincansiper** [comment]
Yes, I can do in that way

**Comment by metincansiper** [comment]
@ugurdogrusoz I implemented it in unstable branch

**Comment by ugurdogrusoz** [comment]
@metincansiper thanks. how come the option specified as a parameter doesn't get set under the Map Properties as set though? Enable Ports looks still true in your example in the inspector for example.
For instance, in the below example, we'd like to see the compartments to be bigger than their contents as set by the user/model:
http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/?URL=http://sbgn.github.io/sbgn/images/learning/iNOS_SBGN-ED.sbgn&allowCompoundResize=true
But when we load this we don't see them as big as specified.

**Comment by metincansiper** [comment]
@ugurdogrusoz I think that option is named as ```allowCompoundNodeResize``` in Newt. It works when I navigate to ```http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/?URL=http://sbgn.github.io/sbgn/images/learning/iNOS_SBGN-ED.sbgn&allowCompoundNodeResize=true```

I think my example uses ```web.newteditor.org``` and most probably the changes are not reflected to there. It works in ```http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/?URI=http://identifiers.org/reactome/R-HSA-6803211&enablePorts=false```

**Comment by ugurdogrusoz** [comment]
You're right, thanks!
