### ISSUE TITLE
Weird behavior on SVG background image

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#273]
On an empty map:
- Create a macromolecule
- Set background image to be this SVG image:
[dh.svg.txt](https://github.com/iVis-at-Bilkent/newt/files/2080192/dh.svg.txt)
Notice how different parts of the image are displayed as background as you zoom in and out.

**Comment by ahmetcandiroglu** [comment]
I changed `viewBox` attribute into `viewbox` in the given svg file and the bug disappeared.

**Comment by ugurdogrusoz** [comment]
I tried doing the same thing with this morning's build but nothing happened (no image set). Then, when I tried to move the node, I got:
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at Object.draw (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:139471:19)
    at Renderer.CRp.drawInscribedImage (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:59397:46)
    at Renderer.CRp.drawNode (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:59983:12)
    at Renderer.CRp.drawElement (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:59161:7)
    at ElementTextureCache.ETCp.getElement (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:61086:7)
    at Renderer.CRp.drawCachedElement (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:59174:36)
    at Renderer.CRp.drawCachedElements (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:59200:7)
    at Renderer.CRp.render (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:60584:9)
    at renderFn (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily/app/bundle.js:58738:9)

**Comment by ugurdogrusoz** [comment]
Btw, a Google search indicates "viewBox" is not invalid if I am not mistaken. I wonder why we choke on it.

**Comment by ahmetcandiroglu** [comment]
File extension should be SVG not txt, otherwise Cytoscape.js does not accept it as an image and throws exception. I will add file and URL validator for this problem since Cytoscape.js does not handle it well.

It seems that SVG files require different encoding method than other image files so I will improve that.

**Comment by ahmetcandiroglu** [comment]
I followed the guideline given in Cytoscape.js docs however zoom bug still appears. Even though "viewBox" is valid only changing it to "viewbox" fixes the problem.

> *SVG image considerations*
Using the viewbox attribute in SVG images may cause render problems in Firefox.
SVG images do not work consistently in Internet Explorer.
Always include this XML header in each SVG image:
`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>`
Use encodeURIComponent to load SVG data.

**Comment by ugurdogrusoz** [comment]
Let's leave this for later

**Comment by nasimsaleh** [comment]
The "svg" tag should have "width" and "height" attributes. "viewBox" attribute is not necessary, it works fine without it. 

Here is a working example with the same svg:
```
<svg width="100" height="100"  xmlns='http://www.w3.org/2000/svg'>
  <rect fill="#039" x="0" y="3" height="95" width="95" rx="15"/>
  <path d='M20,56L19,35C19,30,27,20,33,21L55,21A30,30,0,0,1,20,56Z' fill='#369' stroke='#369' stroke-linejoin='round' stroke-width='5px'/>
  <path d='M17,67A37,37,0,0,0,67,18A36,36,0,1,1,17,67' fill='#FFF'/>
</svg>
```
also note that in the "rect" tag y="3" and both "height" and "width" = "95 which will result on white space on the edges of the node because "rect" is not filling the whole "width" and "height" specified in "svg" tag.

Below is the modified svg file filling the whole node.
```
<svg width="100" height="100"  xmlns='http://www.w3.org/2000/svg'>
  <rect fill="#039" x="0" y="0" height="100" width="100" rx="15"/>
  <path d='M20,56L19,35C19,30,27,20,33,21L55,21A30,30,0,0,1,20,56Z' fill='#369' stroke='#369' stroke-linejoin='round' stroke-width='5px'/>
  <path d='M17,67A37,37,0,0,0,67,18A36,36,0,1,1,17,67' fill='#FFF'/>
</svg>

```
Moreover, we are already using SVG image. The clone image being used in Chise 
https://github.com/iVis-at-Bilkent/chise.js/blob/master/src/utilities/element-utilities-extender-factory.js#L1904 is an SVG image, decoding the data string gives the following svg
`<svg width="100" height="100" viewBox="0 0 100 100" style="fill:none;stroke:black;stroke-width:0;" xmlns="http://www.w3.org/2000/svg" >
<rect x="0" y="0" width="100" height="100" style="fill:#a9a9a9"/> 
</svg>`
