### ISSUE TITLE
Cannot insert whitespace in labels

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#3]
The spacebar doesn't work. Either when double clicking to edit a label on the map, or in the properties tab in the inspector.

**Comment by ugurdogrusoz** [comment]
@metincansiper did we ever have this support or was it broken lately?

**Comment by metincansiper** [comment]
I think that the problem was related to using arrow keys in node-resize extension. In that extension there was a problem of triggering scrolls when arrow keys are pressed to move nodes. Previously, that problem was solved in that extension by preventing the default behaviours of space and arrow keys (That solution created the problem in this issue). However, it seems that now in that extension the default behaviour of these keys are prevented conditionally (By checking if the keys are not pressed on a textbox or a textarea). @royludo The problem in this issue seems to be an old issue, you can try to update node-resize extension on your localhost or you can try chise daily. The way this problem is fixed in extension seems to be enough for now, but I think that a safer way should be searched for (Because, for now we defined the textboxes and textareas as the exceptional cases,  but there may be other exceptions that we are not catched).

**Comment by royludo** [comment]
indeed, I should be more careful with the updates and maybe with the cache also.
