### ISSUE TITLE
Error setting background image from URL

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#327]
https://simgbb.com/images/logo.png

We get No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ahmetcandiroglu** [comment]
It seems that 'Access-Control-Allow-Origin' header must include request source (http://web.newteditor.org) and it is done on the server side. This cannot be done since the user may send a request to any website.

Another possibility is to use proxies which require extra dependency and are complex for our purposes.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Let's revisit this problem. If too much work, we'll skip it for this release.

**Comment by canbax** [comment]
When we are making an HTTP request to an unknown address, it might be needed to add `Access-Control-Allow-Origin: *` to the request header
