### ISSUE TITLE
Compound resize behaves differently

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#357]
Compound resize (after enabling it with Allow Compound Resize) doesn't behave as before. For instance, I am not able to create a wide compound with a single node in it, which is towards left or right (not middle). See the sample "insulin like ...". Try resizing Extracellular as wide as Cytosol, keeping IGF at the left.
This used to work fine in Newt 1.0 (http://www.cs.bilkent.edu.tr/~ivis/Newt_daily.2017.08.23).
Related code is around here:
https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize/blob/master/cytoscape-node-resize.js#L716

**Comment by hasanbalci** [comment]
@ugurdogrusoz The reason for the bug is a logic error occurred in commit https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/c5b9f685610dfab4abce5dcfdeab4b56529508a4 done to fix #49. The commit I did solves the bug and seems to have no side effect for #49, but it would be great if you check it as well.  

I also realized a different behavior related to the compound sizes. For example, if we resize a compound and save the map, when we load it again we lose the change on the compound size. This was working in Newt 1.0. I will also try to solve it.

**Comment by ugurdogrusoz** [comment]
When a compound is resized and loaded back in, do we not see the change in size even when compound resize is enabled?

**Comment by hasanbalci** [comment]
Yes, we don't see the change. I think map is saved correctly, but there is a problem during load operation.

**Comment by hasanbalci** [comment]
[This commit](https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/2109ab34da81f795f4072e8d16199f9c59bb4669) causes the compartments to lose their saved dimensions on load when compound resize is enabled.

**Comment by hasanbalci** [comment]
@ugurdogrusoz @kaansancak [This commit](https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/2109ab34da81f795f4072e8d16199f9c59bb4669) causes the compartments to lose their saved dimensions on load when compound resize is enabled.
