### ISSUE TITLE
Incremental and static layout on toolbar

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#370]
Currently there is a button on the toolbar corresponding to "Perform Layout", and it performs an incremental layout if the associated property is true, and a static (non-incremental) one if it's false.
Instead, we should have 2 buttons on the toolbar, one layout that works depending on the current value of incremental option, one for static layout, *regardless* of the current value of incremental flag in layout options.

Tooltip text for the new button (static):
- Perform Static Layout: Re-calculate layout of current map *from scratch*, ignoring current positions and maintaining compound structures.

Icon (static):
- use "layout-static.svg":
[layout-static.svg.txt](https://github.com/iVis-at-Bilkent/newt/files/2210046/layout-static.svg.txt)

Make sure to update the UI Guide help text accordingly.

Let's add "Perform Static Layout" in between the two operations in the Layout menu as well.

**Comment by hasanbalci** [comment]
A few points:

- I didn't update the tooltip text of the previous icon for now, if you want we can update it.

- Do we need to add static layout operation to Menu, since all operations in toolbar also exist in the Menu. 

- To the UI Guide, I just added the explanation of the new operation as "Perform Static Layout", we can update there as well.
