### ISSUE TITLE
Some style properties of nodes of (at least some) sample graphs cannot be updated in unstable branch

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/newt#371]
Minimum steps to reproduce:

- Navigate to http://ivis.cs.bilkent.edu.tr/ (I think this is where unstable branch is deployed daily)
- Load the sample called neuronal_muscle_signaling and select a random node
- Check the background color of the node from the inspector you will see that inspector shows that the bg color is white though actually it is not.
- Try to update bg color from inspector. Then you will see that background color is updated in inspector but node is still rendered with the same bg color.

**Comment by ugurdogrusoz** [comment]
@metincansiper almost all samples are now using 3d or gradient color schemes, which make use of background images. Due to background images you can't see the fill color. If you remove the image (explicitly on a specific node or by changing the color scheme style to solid) you will see the fill color set.
