### ISSUE TITLE
Improve support for coloring SBGN

### ISSUE THREAD

**Issue by matthiaskoenig** [iVis-at-Bilkent/newt#386]
I just tried to color an SBGN map. This is very cumbersome in with the current color handling of newt and I gave up after 5 minutes. Here some suggestions which would improve coloring of SBGN maps and make it more usable:
- allow setting opacity within the color chooser, i.e. allow RGBA values (which contain alpha value). 
- display the value of fill opacity (this is only a slider, if I want the same opacity for multiple elements I have no idea if they have the same value, i.e. 60% or 70% just based on the slider position
- display the existing colors in the SBGN in the color chooser (or at least the recently selected colors)! One can than quickly select the color from the handful of colors one normally uses). Currently I have for every color to type in the Color Name in RGB than afterwards try to get the opacity slider to the same value. People are using a handful of colors for multiple objects. These have to be accessible quickly.
- allow to color multiple objects at once! Currently I have to select every line and node separately and set the colors. I just want to select a bunch of objects and give them the same border color or same fill color.

**Comment by ugurdogrusoz** [comment]
@matthiaskoenig Thanks for sharing your experience.  Color chooser is platform specific. What platform are you on? OS and browser? 
You can choose and change properties of multiple objects in various ways: 1) shift-left click for multiple selection 2) right click on a specific object and choose "Select Objects of This Type" 3) style one object as you like and then in the property inspector in the right panel click "Set as Default for ...", so that any newly created instances of this object type will get the same style.

**Comment by matthiaskoenig** [comment]
I am using Firefox Quantum v65.0, 64bit on ubuntu linux.
Thanks for the information. In my use case I wanted to use color to distinguish different subsets of elements, i.e., not all elements of one type should be styled in the same manner.

**Comment by ugurdogrusoz** [comment]
Thanks. In that case, you need to manually multiply select all such objects and style simultaneously.
We will look into any improvements we can make with the color chooser.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh Did you make any improvements for this? I remember you looking into a third party library for this.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh please fill in @canbax on the issue

**Comment by ugurdogrusoz** [comment]
Looks good in general on MacOS. I'll try it on Windows tomorrow.

We shouldn't have multiple color pickers visible though. In fact there should be exactly one instance, otherwise colors used in two color pickers won't be accessible to the other one for instance.
<img width="1280" alt="Screenshot 2019-09-30 at 21 01 32" src="https://user-images.githubusercontent.com/3874988/65903849-d437cd00-e3c5-11e9-9fd4-8e438f70a003.png">
