### ISSUE TITLE
Highlight query seed genes / paths

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#389]
We should try to highlight as much of the query seed genes / paths as possible with each query using the [newly implemented highlight feature](https://github.com/iVis-at-Bilkent/cytoscape.js-view-utilities/issues/15).

**Comment by umut-er** [comment]
I am currently using [cytoscape.js-graph-algos](https://github.com/iVis-at-Bilkent/cytoscape.js-graph-algos) to implement highlighting. I found that there is some incongruency between how pathway commons does the common stream queries and how cytoscape.js-graph-algos does common stream queries.
When I query pathway commons for the common stream of PTEN and TP53, pathway commons returns nodes if at least one node that has "PTEN" in its label and at least one node that has "TP53" in its label have access to the node within specified length limits. However, if I query cytoscape.js-graph-algos with all PTEN and TP53 nodes as source, the algorithm only returns nodes if ALL nodes named PTEN and TP53 have access to the same node within specified length limits.
This is problematic because in the context of a pathway commons query because those usually return lots of nodes named "PTEN" and "TP53".
All of this means that there needs to be some additional functionality in the cytoscape.js-graph-algos extension to accommodate this. I can look into it.

**Comment by umut-er** [comment]
Also, there is quite a bit of difference in how `pathsBetween` and `pathsFromTo` return nodes. On the same input, `pathsFromTo` query on [cytoscape-graph-algos](https://github.com/iVis-at-Bilkent/cytoscape.js-graph-algos) seems to return much more nodes than `pathsBetween`. I couldn't quite understand why this happens, it seems kind of counterintuitive to me. I think it might be related to the `furtherDistance` parameter in the `pathsFromTo` query but I am not sure. I guess when the highlighting feature gets integrated we can do some testing. I think query highlighting can be integrated before I start working on underlay highlighting mode.

**Comment by ugurdogrusoz** [comment]
@umut-er I wouldn't worry about the discrepancies (which I am not surprised about btw) in the implementations of queries in this context. Just get the highlighting working as requested.
