### ISSUE TITLE
Context menus do not display

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#41]
Context menus do not display at all or in weird locations after the core upgrade

**Comment by metincansiper** [comment]
This bug seems to be solved now. I solved the problem in master branch of the related extension (and used its master branch in newt) but has not released a new version including this fix. The same applies to other extension as well (I made them compatible with cytoscape.js v3 in their unstable branches if they have it or their master branches if they do not have an unstable branch). We can release cytoscape.js v3 compatible versions of the extensions when we make sure that the codes in that branches works fine.
