### ISSUE TITLE
SIF samples

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#428]
Can you guys please provide at least a couple of SIF files to us to list under Samples?

**Comment by metincansiper** [comment]
@ugurdogrusoz we have SIF sample files to list. How about converting them to ``nwt`` files and storing in that format. Otherwise (if we store them as simple SIF files) we would most probably have to perform layout immediately after the files are loaded as SIF file does not store layout by itself.

**Comment by ugurdogrusoz** [comment]
@metincansiper yes let's save the sample sif files as .nwt since we need layout and style information for aesthetic reasons.

**Comment by ugurdogrusoz** [comment]
Go ahead and prepare the sif samples. I think we can style them if needed.

**Comment by metincansiper** [comment]
@ugurdogrusoz I implemented this in a feature branch. However, it is not ready to be merged into unstable yet. The files can be loaded through load menu item (through ``sbgnviz.loadNwtFile()`` that calls ``sbgnviz.loadFile()``) in the menu. However, they cannot be loaded through ``sbgnviz.loadSample()`` though ``sbgnviz.loadSample()`` is expected to behave like ``sbgnviz.loadFile()`` expect accepting different input format. Which is most likely because the changes introduced by [this if statement](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/file-utilities-factory.js#L222) is done for ``loadFile()`` but not for ``loadSample()``. I think it must be fixed before merging my feature branch. I did not want to make the changes by myself to avoid introducing new bugs. However, I can do it if needed. 

BTW I just read your last comment. I have already applied color schemas to the sif samples in my branch. However, I can remove that colors if needed.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh we need to make sure that conversion related code in ``loadFile()`` needs to be also done in ``loadSample()`` as @metincansiper described.

**Comment by nasimsaleh** [comment]
I changed loadSample in sbgnviz, now it should accept  hyphen separated styles as well.

**Comment by metincansiper** [comment]
@nasimsaleh Thanks! @ugurdogrusoz I merged the changes to add sif samples.

**Comment by ugurdogrusoz** [comment]
Thanks @metincansiper. Both of these (esp. 2nd one) is rather dense, almost a hairball. Can we perhaps make at least one more like a real life network looking?

**Comment by metincansiper** [comment]
@ozgunbabur Do you have any such graph?

**Comment by ozgunbabur** [comment]
They look fine with topology grouping. Is this option turned off by default?

**Comment by metincansiper** [comment]
Probably the default option is overridden by the preferences coming from file I will update it.

**Comment by ugurdogrusoz** [comment]
Yes it's turned off by default. Go ahead and make it true by default if you guys prefer that. Alternatively, the graph could be saved after topology grouping is enabled. Then it would open up with topology grouping on load of the sample.

**Comment by metincansiper** [comment]
I updated the sif samples (actually nwt files) to have that option "true" and override the default properties. I can update the default option as true if needed.

**Comment by ugurdogrusoz** [comment]
@metincansiper They look good now thanks!
