### ISSUE TITLE
Revise SBGN samples

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#458]
Let's revise SBGN samples as follows:
- Export the following samples as *Plain SBGN* and store them in GitHub repo and deployment as .sbgn files: PD: Glycolysis and MAPK cascade, AF: Regulation...
- Other SBGN samples should be saved as .nwt files and stored in GitHub repo and deployment like that.

Please make sure style, bends, etc. are properly restored on sample load.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh After the revision we noticed that *plain* SBGN files in the samples (e.g. Glycolysis and Regulation...) do not load as *samples* (spinner keeps spinning). Please investigate why this might be happening.

**Comment by ugurdogrusoz** [comment]
All samples load fine now. But there are some minor problems:
- Droshophila sample used to have some arcs and processes in red (similar to the pathway [here](https://sbgn.github.io/sbgn/images/published_maps/toure_drosophila.png))
- Some labels in Regulation sample won't fit inside nodes, let's talk how we can fix this.

**Comment by nasimsaleh** [comment]
@hasanbalci saving should take edge style properly now. you can change the samples.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh The only remaining issue now is Regulation .. sample labels not fitting in nodes.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  the issue was with setting default font properties to Biological Types. I tried changing BA to a simple chemical node type and the labels fit. also in the inspector when you click on font properties for a Biological Type it would should undefined values. The Biological Types were forgotten when setting default font properties in sbgnviz. Now it should work.
