### ISSUE TITLE
Incremental layout on topology grouping

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#459]
I think we should use this flag "Rearrange on Complexity Management" and apply an incremental layout as a user enables or disables SIF topology grouping. In other words, when the user sets or resets topology grouping, we should check the mentioned flag, and if true we should incremental layout. We do this on many complexity management operations such as expand/collapse and show/hide.

**Comment by metincansiper** [comment]
@ugurdogrusoz I added this feature but during testing I realized another existing issue related to mixing enable/disable topology grouping and undo/redo in some orders. I am looking into the other issue.

**Comment by metincansiper** [comment]
@ugurdogrusoz looks like the problems related to SIF and this issue itself are solved. However, mixing enable/disable topology grouping and undo/redo is still problematic in terms of layout. However, looks like the problem is not directly related to this issue it is solely caused by undo/redo of layout. I created an issue for that #468.

**Comment by ugurdogrusoz** [comment]
@metincansiper We have the following problems with the current implementation:
- If you *undo* setting / resetting of this flag, the flag gets messed up (it shows unchecked and grouping is done and vice versa).
- We don't take "Rearrange on Complexity Management" flag into account; we always apply incremental layout as this flag is set/reset.

**Comment by metincansiper** [comment]
I fixed the second problem

**Comment by ugurdogrusoz** [comment]
- I am not able to reproduce the first problem either, never mind.
- For the flag, unfortunately I specified the wrong flag, it should have been "Recalculate layout on complexity management", not the Rearrange one. Could you please change this?

**Comment by metincansiper** [comment]
I updated the flag name but looks like mixing undo/redo and enable/disable topology grouping is still causing problems in some cases. I am looking into it.

**Comment by metincansiper** [comment]
I fixed the remaining problem as well. However, I think that it worths mentioning here what the problem was. Because I beleive that some similar problems may occur in the future as well. 

Undo/redo of sif topology grouping operation removes the existing elements and restores the ones removed from the previous operation (which is being undone/redone)(BTW this way would probably be the only possible way because topology grouping operation updates parent of nodes and updates source/target of edges. And the way how the related cy.js facility (``ele.move()``) works makes using this way needed).

However, Newt listens to the node removal events and resets the map type if no element is remained in the graph (https://github.com/iVis-at-Bilkent/newt/blob/unstable/app/js/app-cy.js#L1270). Therefore, when I remove the existing elements the map type is reset which was the reason of the problem. 

I have fixed it by saving the existing map type (supposed to be sif actually) before removing the existing elements (which is followed by restoring the old ones) and then setting the map type back after restoring the old elements (in undo/redo function of enable/disable topology grouping).

It works now but as I mentioned it worths noting here in case someone else run into a similar issue.

**Comment by ugurdogrusoz** [comment]
@metincansiper thanks for catching the complications with setting may type by listening to removal. We decided to revert this behavior (the goal was to avoid getting stuck in "Unknown") with [this](https://github.com/iVis-at-Bilkent/newt/issues/469).

**Comment by ugurdogrusoz** [comment]
I think complications are resolved, we can close now.
