### ISSUE TITLE
Gradient color schemes not working properly

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#478]
- Create a map from scratch
- Apply a color scheme and change the style to *gradient*
- Notice that gradient is not applied properly (it should say go from white to blue, but it's almost all blue)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz The problem is that the png images used as background image to give gradient effect are transparent, i.e. the gradient effect lets say for the a green color goes from no color to green, so if we have a background color it will appear in the transparent area of the png image, I think we should change the png images for gradient to create an effect from white color to the desired color, not from no color to the desired color.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz It seems fine. Thank you.
