### ISSUE TITLE
Keep absolute infobox coordinates on resize

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#513]
Let's keep the absolute infobox coordinates on interactive resize (now that we know how to do that) if that's what the user wants with a setting. We could name this setting "Keep relative information box coordinates on node resize" (yes this breaks a record for a setting name :), which is true by default, as the last option under "Labels".

Also make sure the same idea applies to "Resize node to content" functionality.

**Comment by nasimsaleh** [comment]
keeping the absolute coordinates messes up the undo redo functionality, we cannot batch the undo and redo of resize and keep the absolute coordinate in one operation because they are done in different locations (node resize extension vs newt) it creates inconsistency in behavior. The public newt right now has a little inconsistency after resizing a node that triggers tiling up, more than one undo is necessary to get the previous state.
