### ISSUE TITLE
Padding problem on layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#528]
When layout is called, paddings of compound nodes are not taken into account and assumed to be minimal. We should talk about how to handle non-zero additional compound padding values. Before layout (addtl compound padding: 30):
![padding-prob-on-layout](https://user-images.githubusercontent.com/3874988/73651327-429edb80-4695-11ea-9674-5a15193fe94e.png)
After layout:
![padding-prob-on-layout (1)](https://user-images.githubusercontent.com/3874988/73651329-45013580-4695-11ea-9cee-16f82ef30149.png)

**Comment by hasanbalci** [comment]
@ugurdogrusoz It seems the main reason of the issue is that the compound paddings (especially top and bottom) are not taken into account accurately during the tiling operation in the cose layout.

I also noticed that "Tiling Vertical Padding" and "Tiling Horizontal Padding" options in the Newt are considered as percentages and the actual paddings used during tiling are calculated in the same way compound paddings are calculated before by using the percentage value. In other words, if the average simple node size is 45 and "Tiling Vertical Padding" option is 20, then actual tiling vertical padding is 45*0.20 = 9. We can also consider to use absolute value here as in the compound paddings or the tooltips of these options should be updated (because they give the sense of absolute values).

Lastly, current cose layout assumes that compound nodes have equal padding from each side and it may not work accurately with different padding values on each side. Currently, Newt removes minWidth, minHeight and bias values before the layout and we lose the resized versions of the compounds after the layout.

**Comment by ugurdogrusoz** [comment]
@hasanbalci Let's fix these problems as follows:
- Use absolute padding values for tiling
- Layout should ignore any bias values of compounds but should properly take the current paddings into account, assuming equal paddings on all sides. Let's discuss what the best way to input paddings might be for the layout algorithm. In the case of Newt, different compound node types might have different paddings (complexes vs. non-complexes).
