### ISSUE TITLE
Border width changes on background image use

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#554]
Any particular reason the border width of nodes changes when experiment data is overlaid?
- Load sample experiment map and data (notice how RB1 has thinner border than CCNE)
![p53_rb_pathway](https://user-images.githubusercontent.com/3874988/77100932-807a7800-6a27-11ea-862b-8fc6d0aace9b.png)
- "Remove All" (notice how border width are the same for all nodes)
![p53_rb_pathway (1)](https://user-images.githubusercontent.com/3874988/77100962-8cfed080-6a27-11ea-8ba3-ce19291d7248.png)

**Comment by mervekilicarslan5** [comment]
I think this issue is not related to the experiment data overlay. I tried setting a background image manually and border width was thinner. I believe it is predefined somewhere in the node functionalities. 

![image](https://user-images.githubusercontent.com/45542119/77103546-9c801880-6a2b-11ea-84d2-fe26732aef8a.png)

**Comment by nasimsaleh** [comment]
@ugurdogrusoz The border is not thinner, half of it is hiding behind the background image, if you set background image then decrease opacity to see through it, you will see the full border. I guess when we sit background color width to 100% it covers all the width of node which includes half the border thickness.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh can you please check various options for background images and see if there is one that avoids this problem? Also any way we can change the drawing order of border and background image? Please see if there is a related ticket in Cytoscape.js repo.

**Comment by nasimsaleh** [comment]
This same issue is reported [here](https://stackoverflow.com/questions/41651604/nodes-background-image-is-clipped-when-using-border). Max suggests setting a padding equal to half the border width.

**Comment by nasimsaleh** [comment]
Following the above solution by increasing padding won't work, because we have to set the option "background-width-relative-to" to "inner" so it doesn't include padding when calculating the width of background image, which will create problem with compound parent nodes background images which wont cover all the node since it will ignore the padding.

**Comment by ugurdogrusoz** [comment]
Let's ignore this for now.
