### ISSUE TITLE
Review tooltips

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#571]
Newt has tooltips in the right panel (e.g. Map) and in other settings dialogs (e.g. Layout Properties) on setting names as well as buttons. Let's review these.

**Comment by hasanbalci** [comment]
I reviewed tooltips in Map and Layout Properties, Palette and toolbar. I think we don't use tooltips anywhere else. A few points to consider:
- [ ] Tooltip of "Additional Compound Padding" should be updated because it mentions about percentage. 
- [ ] In tooltip of "Label Size" it says, "small, medium or large" but real options are "small, regular, large".
- [ ] A tooltip can be added for "Load..." in Experiment section.
