### ISSUE TITLE
Clone marker lost on color scheme

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#574]
With at least *Perturbing agent* and *Unspecified entity*, if you mark these as *cloned*, and then change the color scheme to be something non-default, you lose the clone markers. 
This is not the case normally (see Macromolecule) for instance. So I guess with some node types we don't use the same mechanism as others for rendering clone markers?

**Comment by nasimsaleh** [comment]
Normally, for any node type other than _Perturbing agent and Unspecified entity_, cloning is done at the core rendering level.  However, this [issue](https://github.com/iVis-at-Bilkent/newt/issues/267) was resolved by implementing the cloning functionality for _Perturbing agent and Unspecified_ entity by setting a background image. That's why changing color scheme removes the cloned shape.

**Comment by ugurdogrusoz** [comment]
Then, in the long run, we should:
- either render clones of these two node types at Cytoscape.js core as well
- or allow multiple background images to *live together* (nodes can have multiple background images actually)

**Comment by ugurdogrusoz** [comment]
@msalihaltun let's discuss before you work on this

**Comment by ugurdogrusoz** [comment]
This problem seems to be fixed but I see other problems (whether related with the fix or not I am not sure):

- [ ] When you change the color scheme (using a background image) for unspecified entity or perturbing agent with a background image, you see the entire background painted as clone marker:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/3874988/98916280-062dc500-24dc-11eb-8b80-b378349bcb17.gif)

- [ ] With the above example, undo takes 2 tries to get it undone (not just 1)
