### ISSUE TITLE
Some load from URL parameters set too late

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#586]
As can be seen in section "Launch with a remote SBGN map" in [here](http://newteditor.org/tutorials.html#file-operations), we are supposed to be able to change settings when loading from URL. 

However, as can be seen with [this](http://web.newteditor.org/?URL=https://cannin.github.io/covid19-sbgn/Viral_entry_V01.xml.sbgn&inferNestingOnLoad=false), even when we explicitly set "infer nesting on load" to false, compartments are inferred. Try loading [the same SGBN map](https://cannin.github.io/covid19-sbgn/Viral_entry_V01.xml.sbgn) to a local Newt with this setting being true and false to see the difference.

According to @hasanbalci, this is since we set this particular setting too late during load. This is probably the case with some other options for remote launch. So, if possible, we should set some settings earlier (before they are actually used). Let's discuss.

**Comment by hasanbalci** [comment]
`inferNestingOnLoad` and `compoundPadding` parameters were being set too late, now it's fixed and they're set before file is loaded. 
`inferNestingOnLoad` is considered as true for "Load from URL" and as false for "Load from URI" by default as before. However, user can now change this setting by providing `inferNestingOnLoad` parameter in URL or URI.
`compoundPadding` parameter works if the file to be loaded has "extension" section. Otherwise, I think `compoundPadding` is calculated automatically.

**Comment by ugurdogrusoz** [comment]
Great thanks. Let's also make the default for `inferNestingOnLoad` false in both URL and URI cases (was true for URL).

**Comment by hasanbalci** [comment]
`inferNestingOnLoad` is now false by default for both URL and URI.

**Comment by ugurdogrusoz** [comment]
Documentation says `allowCompoundNodeResize=false` but it's not.

**Comment by ugurdogrusoz** [comment]
The behavior should be as follows:
- For the following two options `compoundPadding` and `inferNestingOnLoad`, we should ignore any value specified for these in the file.
- For remaining options, we use the values in the file only when they are explicitly specified as a parameter during remote launch.

**Comment by hasanbalci** [comment]
Now this is the case:

- For `compoundPadding` and `inferNestingOnLoad`, we use the values coming from URL/URI parameters if set by the user, otherwise we use the default values. 
- For other properties, we use the values in the following priority: URL/URI parameters set by user, map properties defined in file, default values.
