### ISSUE TITLE
Inconsistent way to open external database pages

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#611]
We do not have a consistent mechanism to open the associated external database page of macromolecules and small molecules. Let's discuss this and try to fix it.

**Comment by msalihaltun** [comment]
Currently, we use buttons with links to GeneCards when genes are selected and we fetch data to be displayed from ChEBI when simple chemicals are selected. There is no fetch operation available for GeneCards at the moment. I think, for now, we should have the accordion toggle automatically opened when we show buttons, and for simple chemicals, we should automatically open the toggle after the data fetch operation is completed. This will make it so that users don't have to make an extra click to reach data from external database pages.

**Comment by ugurdogrusoz** [comment]
Makes sense, thanks.
