### ISSUE TITLE
Highlight bug for edge cardinality

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#621]
When you highlight an edge with a cardinality, the cardinality stays in selection color (even though the edge is no longer selected) until a re-rendering takes place.
![Screenshot 2020-10-06 105649](https://user-images.githubusercontent.com/3874988/95174381-a6e4e280-07c2-11eb-9877-46629a48391b.png)

**Comment by msalihaltun** [comment]
I noticed another problem while inspecting this bug. When I have highlighted edges which have cardinality that is displayed properly - after a re-rendering of the above bug - and I select multiple edges, then proceed to unselect by clicking anywhere, the cardinality styles won't update - they stay in selection style instead of highlight. Meanwhile a single edge selection followed by an unselect will update the cardinality style.
