### ISSUE TITLE
Losing edge selection on drag

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#623]
If you drag / move a group of nodes and edges that are selected, you lose the edge's selection state. I am pretty sure we did this to avoid some bug with edge reconnection handles and/or anchor points. Let's re-visit and see if we can fix this.

**Comment by msalihaltun** [comment]
I have considered the following issues and the respective fixes made in `cytoscape-edge-editing`: https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/28, https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/29. 

Removing the workaround of unselecting edges on drag doesn't seem to cause an issue. This might be the result of work to fix the following issues: https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/43, https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/44; in which we were also trying to solve problems where anchors and/or reconnection handles either wouldn't be drawn or be drawn in incorrect locations.

There is some performance concerns cited in https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/29 with layouts, but I believe that shouldn't be a problem while using a `drag` event instead of `position`. @hasanbalci can confirm whether this is the case.

With the fix, edge selection should not be lost on drag, and nodes should not lose selection when a non-selected node is dragged.

**Comment by ugurdogrusoz** [comment]
Looks good to me. @hasanbalci Please test.
