### ISSUE TITLE
Update Quick Help with new shortcuts

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#631]
Quick Help section should be updated with newly-added/missing shortcuts for users to know about them. The two I noticed are "Alt + taphold" for the selection of objects with the same type and "Shift + taphold" for selection of the neighbors of node/edge. Currently written "Click + drag on selected edge: Add and place a bend point" should also be updated.

**Comment by ugurdogrusoz** [comment]
Right before "Arrow keys", let's add:
- Shift + taphold on node/edge: Select neighborhood of node/edge (involved processes for PD maps)
- Alt + taphold on node/edge: Select all nodes/eges of this type

**Comment by msalihaltun** [comment]
I think we should maybe remove "Click + drag on selected edge: Add and place a bend point" as @hasanbalci mentioned since this is not possible anymore. We could use a new description of how anchors are created, or don't mention them on the help modal since they are now created from context menu (not a shortcut or 'hidden' feature).

**Comment by msalihaltun** [comment]
There is a couple of double colons at the top two options, must have been a typo. Will also remove those when I make the changes.

**Comment by ugurdogrusoz** [comment]
@msalihaltun Updated to do list along your comments
