### ISSUE TITLE
Format for experimental data incompletely specified

### ISSUE THREAD

**Issue by rmtfleming** [iVis-at-Bilkent/newt#636]
I am trying to generate a file suitable for experimental data import, however, the information in the tutorial
http://newteditor.org/tutorials.html#experiment-data
is insufficient.

Please could some experimental data examples be added to the samples folder, that match some of the sample neworks:
https://github.com/iVis-at-Bilkent/newt/tree/master/app/samples

This example is too simplified and is generated within the javascript rather than coming from a .txt file, so it is not very useful.
https://github.com/iVis-at-Bilkent/newt/blob/d0e1c11503236376d8982c69d9463d185bad474a/app/js/app-menu.js#L416

The example given here, it is not clear to which networks they relate to:
http://newteditor.org/samples/sample-experiment-file.txt
http://newteditor.org/tutorials.html#experiment-data

Here are some ambiguities that need to be specified more clearly in the documentation:

name	sample experiment data
description	Adenoid Cystic Carcinoma 2014 vs 2019
el	2014	2019
RB1	36	12
TP53	36	72
CDKN2A	0	14
MDM2	0	5
CCNE	0	7

version\t1.0
name\tsample experiment data
description\tAdenoid Cystic Carcinoma 2014 vs 2019
color\t0\t#FFFFFF\t100\t#FF0000
gene\t2014\t2019
RB1\t36\t12
TP53\t36\t72
CDKN2A\t0\t14
MDM2\t0\t5
CCNE\t0\t7

1) Are RB1, TP53, etc, glyph id's or are they glyph label's? They should not be labels because it is the id's that are unique.

2) What is el in the example above? What is gene in the example above? Which one does it have to be, or does it matter?

**Comment by rmtfleming** [comment]
Part of the issue appears to be that formatting characters are misinterpreted at the end of lines.
e.g. 
Water\t0\t\n
will not load, whereas
Water\t0\n
will.

**Comment by ugurdogrusoz** [comment]
1. Since glyph ID's generated by Newt and many other similar tools are not human understandable (e.g., "_82f19e9e-6aa2-42b3-8b5e-8cee17197085"), we go with the labels. Besides in an SBGN PD map, IDs of multiple states of an entity will be different but we want to show the same experiment data on all states of the same entity.

2. "el" or "gene" are just titles/names for the column, place holders, and what they are doesn't matter.

The sample experiment data ([file](http://newteditor.org/samples/sample-experiment-file.txt)) is for the sample SIF map (that loads on Experiment > Load Sample). Can be found [here]() as well.

You are not supposed to actually put "\t" or "\n" but corresponding (tab and new line, resp.) characters in your files.

It'd be highly appreciated if you [contact us](http://newteditor.org/contact.html) with these problems rather than directly creating issues for them unless you think they are for sure bugs. Thanks.
