### ISSUE TITLE
Applying layout on launch by URL

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#650]
http://newteditor.org/tutorials.html#remote-launch
Let's add a new option "applyLayout" to these to perform layout upon launching by URL, which is false by default.

**Comment by msalihaltun** [comment]
@hasanbalci can you check the layout properties I used in the implementation and tell me if there are any problems?

**Comment by hasanbalci** [comment]
@msalihaltun These options generally apply on launch by both URL and URI, however, in this case it is only required for launch by URL. Therefore, it may be good to rename the new option as "applyLayoutOnURL", because launch by URI requires layout regardless of any option (and currently layout is applied each time on launch by URI). Based on this, you should consider the option only for launch by URL. In addition, layout options seem ok, but we generally call `applyLayout` function to perform layout as [here](https://github.com/iVis-at-Bilkent/newt/blob/b7961b79a74e91a1454efa2a73c2dba8a50268ae/app/js/app-menu.js#L1191).

**Comment by hasanbalci** [comment]
@msalihaltun I think the value of `applyLayoutOnURL` option taken [here](https://github.com/iVis-at-Bilkent/newt/blob/8a091f9cd03af1407fcc0f7136fb2a8036fb4384/app/js/app-menu.js#L632) should be returned to boolean, otherwise it will always be evaluated as true in the following if statement because it is a string. Currently, assigning false value to the option applies layout to the map.

**Comment by msalihaltun** [comment]
Should be okay now.

**Comment by hasanbalci** [comment]
It's working correctly, thanks!
