### ISSUE TITLE
SBML conversion problems

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/newt#655]
Continuation of [this PR](https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/213).

Issues mentioned [here](https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/213#issuecomment-811844987) and [here](https://github.com/iVis-at-Bilkent/sbgnviz.js/pull/213#issuecomment-812526644) still persist.

**Comment by piotr-gawron** [comment]
Dear @msalihaltun, 

I checked the code and it looks like the blue is a default color assigned to compartments when none is provided. Normally it would be overridden by color from sbgn render. But in the sample that you provided you use background image instead of color. Images are currently not supported - I have it on my TODO list to add it. However, support of background image in SBML is limited - SBML does not allow to provide URL based images, only local files are supported. You can check it here: http://co.mbine.org/specifications/sbml.level-3.version-1.render.version-1.release-1.pdf:
>An Image has a required attribute href of type string which encodes a reference to an external JPEG or PNG file.
The reference must be an absolute or relative path to a local file. Non-local image resources (e.g., from the net) are
currently not supported.

So even if I implement it the problem would persist (the image will be lost on one point in translation, because sbml does not support URL files, and SBGN does not support local files which is mutually exclusive :))

I can use black as default (I'm not sure why it's blue, it was developed years ago by a student and maybe @amazein asked for blue directly.

**Comment by msalihaltun** [comment]
Hello @piotr-gawron, thank you for investigating the issue. 

We decided that the color is not a problem. Now that we know where it is coming from, there is no issue on our end. So I'm closing this now.
