### ISSUE TITLE
Sender for email notifications on e2e test failures

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#673]
Let's change this from newtforminerva@gmail.com to newteditor@gmail.com. Also, why do we have newteditor@gmail.com in both To and CC (not that it matters but still)?

-------- Original message --------
From: newtforminerva@gmail.com
Date: Mon, Jun 7, 2021, 12:36 AM
To: newteditor@gmail.com
Cc: newteditor@gmail.com
Subject: Error in end-to-end test of newt
There is error in this test. This test should be recorded in cypress dashboard. You can check it from https://dashboard.cypress.io/projects/m5jo3x/

**Comment by msalihaltun** [comment]
The mail sender is set as newforminerva@gmail.com because sending an email from inside the code using an environment variable is not a safe operation and we remove security features from the gmail account to access it. We don't want to do this with newteditor@gmail.com. 

I did remove the duplication in cc part.

**Comment by hasanbalci** [comment]
I think we should keep the CC part. Because when we merge to master, we change the To part with the actual minerva email and CC to newteditor@gmail.com to get a copy.

**Comment by hasanbalci** [comment]
Sorry, I assumed that we removed it from actual code. We can remove it from the test code, so there is no problem.

**Comment by ugurdogrusoz** [comment]
This is for e2e Newt tests, not for reporting Minerva service issues though?

**Comment by hasanbalci** [comment]
@ugurdogrusoz Yes, it's my misunderstanding, sorry.
