### ISSUE TITLE
Convert PD to AF using service

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#680]
We should implement a conversion operation of PD maps to AF maps and open the AF maps constructed in a new Newt tab. Let's do this in a separate branch or as a PR for now.

**Comment by ugurdogrusoz** [comment]
UI improvements on PD2AF conversion facility:
- [ ] 1. Rename menu item "Convert PD2AF" to "Convert PD map to AF map"
- [ ] 2. Rename root context menu item as "Convert PD map to AF map" as well
- [ ] 3. Name the AF map constructed as the same as the original one with " AF" appended to the name

Issues/bugs:
- [ ] 10. When you open the root context menu and then (without calling an operation and closing the context menu) switch to another tab, the context menu stays. This does not happen in daily build, only on this branch.

**Comment by acanalpay** [comment]
For UI improvements, commit 8f40f2ba356a9dfc24398644f73299a72df7de31 address to problem 1 and 2

**Comment by acanalpay** [comment]
There was a bug when adding map description to the new AF map, PD map description also changed and become AF map's description. Commit 1667d9697dc5cf7c0bb6a31e87526d7e0bfa8781 fixed that bug

**Comment by hasanbalci** [comment]
A few points I noticed during testing:

- [ ] After conversion, while loading converted file, we can set inferNestingOnLoad to true temporarily, because otherwise we lose nesting relation in the loaded map. For example, we change this attribute temporarily while loading results of Pathway Commons queries like [here](https://github.com/iVis-at-Bilkent/newt/blob/70881a5f75d192b3d726706f531f0cc398d83477/app/js/backbone-views.js#L2305). 
- [ ] Sometimes conversion takes a long time (e.g. mammalian_cholesterol.nwt sample takes 15 secs in my case). It would be good to check whether there is any performance problem in our side or it is totally because of the conversion service. In addition, user should know that the conversion is in progress especially for these long cases, so when user click on the conversion button we can show the spinner as we do in Pathway Commons queries or during layout.

**Comment by acanalpay** [comment]
During some tests, we encountered some problems:
1- Collapsed nodes still converted and expanded in the AF map
2- After conversion, some hidden node's compartments are displayed

**Comment by ugurdogrusoz** [comment]
11. infer nesting on load should be set back to its original value (default false) after the conversion (it stays true even if the original value is false)

**Comment by acanalpay** [comment]
While loading the converted map on the new tab, the spinner is not centered.
