### ISSUE TITLE
Prepare a legend for SBML

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#696]
@SelbiEreshova Can you tell me where to find this information? Which node can connect to which type of node via what kind of edge?

**Comment by SelbiEreshova** [comment]
@ugurdogrusoz The legend for SBML is similar to CellDesigner's: https://www.celldesigner.org/help/images/components42.png
Also, you can see the exact rules in the GSoC report: https://docs.google.com/document/d/17Yp1YPOVLc3PJYNRKO9FeCiH_bzyK8rVv08jGs3ilyQ/edit?usp=sharing

**Comment by ugurdogrusoz** [comment]
@umut-er Other Legends (see under Legend menu) have been prepared using Inkscape and used in .svg format. Please use the same format/style and create one for SBML (now that Newt 4 supports an SBML palette).

**Comment by ugurdogrusoz** [comment]
Looks good thanks. One minor improvement: can we increase the width of the window so that the title fits in a single line?

**Comment by umut-er** [comment]
This worked on my local computer. Next deployment is at 19.30. If it doesn't work on the server I can change it again.

**Comment by SelbiEresh** [comment]
@umut-er 
There seems to some minor mistakes in the notation:
1. Translation consumption and translation production. Notice that the line should be __.__ instead of __..__ Otherwise there is no difference between translation and transcription.
2. The edge 'negative influence'
3. The edge 'unknown reduced stimulation '

Please refer to cell designer's legend for correct notation : [https://www.celldesigner.org/help/images/components42.png](url)

**Comment by umut-er** [comment]
Hey, thanks for the review! It should be fixed now. We can close this issue.

**Comment by ugurdogrusoz** [comment]
Please confirm @SelbiEreshova [here](http://newt.cs.bilkent.edu.tr/)

**Comment by SelbiEresh** [comment]
Yes, it looks correct now. Thank you @umut-er!
