### ISSUE TITLE
Make map type more apperant

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#715]
Currently, we have maps of these types: SBGN: PD, AF, PD+AF, SIF, SBML, and All. One can see the map type under Map Properties:
![image](https://github.com/iVis-at-Bilkent/newt/assets/3874988/996dbadc-c61e-4211-b169-dbf56a7220de)

In order to make this more apparent, let's also display it somewhere like here:
![image](https://github.com/iVis-at-Bilkent/newt/assets/3874988/3bd56352-c57c-45f0-9656-42155733a1fc)

Notice that when the user changes the map type, this should be properly updated.

**Comment by umut-er** [comment]
The baseline functionality for this has been done. It currently looks like this:
<img width="557" alt="Screenshot 2024-06-25 at 16 52 58" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/0675b938-8b04-40e4-9dc5-09f71eb21829">
let me know if something is wrong. There are two issues that I am aware of:
1 - When loading samples, we only get PD as the type.
2 - When changing map type with an undo operation, we can't change this indicator.

PS. The internal server appears to be down. I haven't uploaded these changes there yet.

**Comment by umut-er** [comment]
Other potential concerns include:
1 - remote launching
2 - importing
if you have additional scenarios in which this feature could potentially fail (currently it works when new empty map is created and when the map type is changed using the sidebar (map -> general -> type)), please add them below.

**Comment by ugurdogrusoz** [comment]
Looks good. Can we make the style of this label different by reversing the colors? Background black, font color white for instance.

**Comment by umut-er** [comment]
I think this should be mostly done. The changes are now merged. Please review.

**Comment by ugurdogrusoz** [comment]
Looks great. Let's also make sure we use a consistent naming all around (see yellow marked parts):
<img width="1325" alt="Screenshot 2024-06-26 at 08 06 26" src="https://github.com/iVis-at-Bilkent/newt/assets/3874988/b9cdc110-9829-47d3-967b-0e1c3e2befde">

PD+AF
PD+AF+SIF+SBML (ALL in tab labels due to space constraint)

**Comment by umut-er** [comment]
For the second part:
---
I wondered about the weird border as well. I don't think my changes are directly related to that weird corner shape but I will take a look at it.

For the first part:
---
I am confused about this image. The actual active map (which is currently of type ALL) is not one of those that are shown in the image (bottom left), right? Because that would imply a type inconsistency between the map type and the tab label.  
  
From what I can understand we want to change this "Hybrid(PD,AF...)" text on the image to "PD+AF+SIF+SBML" (and the same for PD+AF). Is that accurate?

**Comment by umut-er** [comment]
The tabs currently look like this on my local:  
  
<img width="574" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/5345f179-fa15-41bc-a27b-bef1ed7dbb8f">  
  
I added box shadows and removed the left border. The following are the new error messages:  
  
<img width="496" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/346b846d-f380-48b2-a03e-c6bd4019feb9">
<img width="495" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/dd59ffb9-4d68-4ff5-9a41-f9e43a32a3b9"> 

---

Here is a overview of what has been done to resolve this issue:  
1. A new html element (a div) is added to display the map type. The positioning is handled similarly to the close tab symbol.
2. Importing, opening a sample and remote launching are handled from a single place. These trigger either "sbgnvizLoadFileEnd" or "sbgnvizLoadSampleEnd" events. We just change the tab label when we encounter these events.
3. Changing the map type from the sidebar is handled seperately as it works somewhat differently from the others in the background (because it doesn't create a new map and it is undoable).
4. **DETAIL ALERT:** For requested change number 2 (number 1 is trivial), I found that weird border thing happened because of a -1px bottom margin on the parent \<li\> item. This caused the last 1px of the border to not properly render. I however couldn't remove this -1px margin as it came from a library (I think) and not from our code.  Instead, I matched the border radius of the child element to that of the parent element. This causes the issue to go away because there is no disagreement between the elements and hence no weird rendering. I also removed the left border and added some box shadowing which I think looks cool.

Please review this issue and close it if it is appropriate.

**Comment by ugurdogrusoz** [comment]
This looks great! The only last improvement I can suggest is making the shadow color of non-current tabs **lighter**.

**Comment by umut-er** [comment]
Here is a preview:  

https://github.com/iVis-at-Bilkent/newt/assets/102927626/19ba1d6e-8a45-4e43-9f1d-fc2b1a39a714

Is this OK or should there be more contrast?

**Comment by ugurdogrusoz** [comment]
Did we accidentally modify the style of the tabs on the right side (should be gray background, dark gray/black font and more compact - less padding)?
Now:
<img width="349" alt="Screenshot 2024-06-26 at 17 19 33" src="https://github.com/iVis-at-Bilkent/newt/assets/3874988/f95ccf42-0c60-4ee7-b5c1-7259946652b2">

Was:
<img width="359" alt="Screenshot 2024-06-26 at 17 20 01" src="https://github.com/iVis-at-Bilkent/newt/assets/3874988/0a0832d4-3c30-4fda-abd3-9f49a43d2b05">

Let's change it back.

**Comment by umut-er** [comment]
Yes, this issue was indeed introduced by me in commit 5a2e78cd2fc2cc2052cd88d0af1cb80ea1579016 (which is the first commit I made about this issue). It was a minor oversight on my part and resolved by putting some code I deleted in the aforementioned commit. I made sure that this error was contained to the elements you pointed out and not present anywhere else after I fixed it.

**Comment by ugurdogrusoz** [comment]
Now it's back to what it was but not consistent with document tabs, can we make these right panel tabs to have a shadow as well similarly?

**Comment by ugurdogrusoz** [comment]
Can we make the shadow of the active right panel tab darker, similar to the active document tab?

**Comment by hasanbalci** [comment]
I get error in the console when I try to change map type from map properties (map -> general -> type).

**Comment by umut-er** [comment]
Apparently one of Noor's commits (c99b32d0d900cf684c3cbe0cb899085ea48b8937) overwrote one of my changes accidentally. I changed it back. Please see it yourself on the internal server.
