### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#72]
- Rename File > Properties... as File > Map Properties...
- Rename "<icon> Properties" as "<icon> Object"
- Move contents of this dialog to a new tab on the right panel as "<settings icon as is> Map" (between "Object" and "Palette")
- Organize contents under "Map" into sections:
    o General
        - Compound Padding
        - Allow Compound Node Resize
        - Enable Ports
    o Labels
        - Label Size
        - Display Labels For Named Complexes
        - Adjust Node Label Font Size Automatically
        - Fit Labels To Nodes
        - Fit Labels to Information Boxes
    o Rearrangement
        - Rearrange After Expand-Collapse
        - Animate On Drawing Changes
    o Color Schemes (new)

**Comment by royludo** [comment]
@ugurdogrusoz I did the changes. Some remarks:
- I added several new color schemes to test.
- for the color schemes, the radio button on the left may not be a good idea finally. It will be a small nightmare to manage the undo/redo of this radio button selection, because it doesn't represent any state of the map. We could make the color scheme as a property of the map. But a color scheme is just something that is applied once. Then you can change everything, assign completely different colors, and the color scheme chosen won't have any sense anymore. I suggest we remove the radio buttons.
- there was a Default button on the General properties dialog box to reset all the properties. Where should we put it now? One default button for each section of the Map tab?
- I've put the new "Allow Compound Node Resize" in the General section, tell me if it's ok there.

**Comment by ugurdogrusoz** [comment]
Looks great with a quick look. I'll investigate in detail and we'll make necessary improvements as suggested.

**Comment by ugurdogrusoz** [comment]
Any outstanding issues mentioned / remaining will be handled separately
