### ISSUE TITLE
Test release candidate

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#725]
We are near completion of Newt 4.0. Let's do a thorough testing before we release it (see [this](https://docs.google.com/spreadsheets/d/1yZqkJjcGpsVQZrt8UZsnWDrtGy6ZLhrj3O_3BDaiacE/edit?usp=sharing) for what to test). 

Check completed in the sheet when you're done and remove your assignment of this issue as well.

**Comment by okg21** [comment]
In the Right Panel section of tutorials there is a statement: 
```
When the object is a macromolecule or a similar entity, a section named "Properties from
GeneCards" will appear. If the user clicks on the button titled with the symbol of the entity
available under this section, the corresponding page in GeneCards, if any, will be opened in a
separate tab. 
```

But the link is opening in the same tab.

**Comment by umut-er** [comment]
<h2>Since this post is very long this is a summary:</h2>
I found a bug about color schemes, more specifically loading a `solid` color scheme map on top of a `gradient` or a `3D` color scheme map. There is a video of that below. I think I fixed this bug but I am not sure. I think someone more familiar with the code should insure that I didn't interfere with any other functionality. 


<h2>Detailed explanation begins here</h2>
Here is a bug I detected with item 4 (file operations). This is specifically about color schemes.

If a sample or file with color scheme of type `solid` is loaded on top of a another already existing map of color scheme `gradient` or `3D`, the colors won't be rendered correctly on the map even though it will be shown correctly on the sidebar. Refer to the video below:


https://github.com/iVis-at-Bilkent/newt/assets/102927626/eb6a2e95-1ab0-4726-b97e-0190636a2235


I determined that this issue is caused by not properly deleting the background image. I tried to fix this and it seems to be gone. Here is the code I changed (this is in newt app-menu.js lines 823-839):

```js
if(currentGeneralProperties.mapColorSchemeStyle == 'solid'){
  for(var nodeClass in appUtilities.mapColorSchemes[currentGeneralProperties.mapColorScheme]['values']){
    classBgColor = appUtilities.mapColorSchemes[currentGeneralProperties.mapColorScheme]['values'][nodeClass];
    // nodeClass may not be defined in the defaultProperties (for edges, for example)

    // NEW CODE
    var bgObj = chiseInstance.elementUtilities.getBackgroundImageObjs(cy.nodes());
    chiseInstance.removeBackgroundImage(cy.nodes(), bgObj);

    // OLD CODE
    // if(nodeClass in chiseInstance.elementUtilities.getDefaultProperties()){
    //   chiseInstance.undoRedoActionFunctions.setDefaultProperty({class: nodeClass, name: 'background-image', value: ''});
    //   chiseInstance.undoRedoActionFunctions.setDefaultProperty({class: nodeClass, name: 'background-color', value: classBgColor});
    // }
  }
}
```

I found the new code after inspecting how the manual removal of background images works. You can see the button related to that:

<img width="285" alt="image" src="https://github.com/iVis-at-Bilkent/newt/assets/102927626/cc3549ff-ea8f-4eb4-bb4f-fe5fecfebd65">

and here is the code related to that button (found at newt inspector-utilities.js lines 817-821):

```js
$('#inspector-delete-bg').on('click', function () {
  var bgObj = chiseInstance.elementUtilities.getBackgroundImageObjs(selectedEles);
  chiseInstance.removeBackgroundImage(selectedEles, bgObj);
  updateBackgroundDeleteInfo();
});
```

as you can see, I copy pasted it almost one-to-one and it seems to be working. However, I don't exactly understand what the old code does and why it doesn't work. I think someone more knowledgable than me should review this change and insure that it doesn't get rid of other functionalities that we might want.

**Comment by ugurdogrusoz** [comment]
> In the Right Panel section of tutorials there is a statement:
> 
> ```
> When the object is a macromolecule or a similar entity, a section named "Properties from
> GeneCards" will appear. If the user clicks on the button titled with the symbol of the entity
> available under this section, the corresponding page in GeneCards, if any, will be opened in a
> separate tab. 
> ```
> 
> But the link is opening in the same tab.

What browser are you using @okg21 ? This behaves as described on my Macbook with Chrome.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @okg21 for introduction part, sif relation link(http://www.pathwaycommons.org/pc2/formats#sif_relations) on Quick Help modal does not open.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz I think there is some problem in PathwayCommons, we don't get any response from PathwayCommons query. It gives request timed out.

**Comment by umut-er** [comment]
PathwayCommons is fine now.

**Comment by ugurdogrusoz** [comment]
There might be two reasons:
- they are working on a new release, the server goes down and up frequently
- you might be doing a very long query
Queries have been tested quite well, please test other parts.
