### ISSUE TITLE
SBML persistency issues 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#739]
- [x] 1. If we mark an SBML node as multimer, hypothetical or active, when we export and import the map again, that node is imported as simple molecule. We lose original node type and its status.
- [x] 2. Omitted process and uncertain process nodes are also imported as simple molecule after an export-import operation and edges connected to these nodes are lost.

**Comment by umut-er** [comment]
I am planning on addressing item 1 here and issue #738 together.

**Comment by umut-er** [comment]
For item 1 the nodes shouldn't lose their type now. For preserving status, we will need to wait on #738. Maybe we should just tick it here and move the status issue there.

**Comment by umut-er** [comment]
@hasanbalci item 1 should be done. Please check it.

**Comment by umut-er** [comment]
I am assigning myself to resolve item 2, if there are no objections.

**Comment by umut-er** [comment]
I think the issue is slightly different now. We can correctly export all process types but for processes other than the normal one, there is a port connectivity issue after export -> import. I think someone more familiar to the port connectivity issue should take over, since there have been some changes related to that topic over the last couple of days.

**Comment by ugurdogrusoz** [comment]
I can confirm that now exporting and importing back omitted processes and uncertain processes work but without port connections. 
Before export:
![new_file (1)](https://github.com/user-attachments/assets/5c241826-4084-4b65-af00-3567bc335d9b)
After export and import back (do not worry about the location of the process being incorrect; @okg21 is already working on this):
![new_file (7)](https://github.com/user-attachments/assets/efa55e7a-473a-4256-9f24-0d62798072a9)

What we need to do with these process node types on import should be similar to what we currently do on importing regular processes' consumption and production edges (this works properly for regular processes).

**Comment by umut-er** [comment]
So, this had nothing to do with the port code. It was caused by a function trying to determine the process nodes by node.startsWith("process") rather than node.endsWith("process"). I noticed it while working on #712. I think this should be good to go after server rebuild @NoorMuhammad1 @ugurdogrusoz.

**Comment by ugurdogrusoz** [comment]
All looks good to me @hasanbalci Please verify and close if ok.

**Comment by hasanbalci** [comment]
Is there any reason that we get the port ordering different after export and import (before export - after import):
<img width="349" alt="Screenshot 2024-08-03 at 11 15 08" src="https://github.com/user-attachments/assets/4633731c-6aaf-466a-a475-e4033cabcdb0"><img width="337" alt="Screenshot 2024-08-03 at 11 15 25" src="https://github.com/user-attachments/assets/50e9bf66-71fa-44a1-a593-d9d673c9e4be">

**Comment by umut-er** [comment]
Yes, I am aware of this issue. See [this](https://github.com/iVis-at-Bilkent/newt/issues/712#issuecomment-2265127795). It is a work in progress over at #712. This can be closed.
