### ISSUE TITLE
Export/import problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#743]
- [x] 1. Load PD sample "PolyQ ..." and then export as "SBGN-ML Plain". Exports fine but on loading the exported file we get "Incorrect File Format". This works fine with some other samples.

- [x] 2. Load PD sample "PolyQ ..." and then export as "CellDesigner", we get "Conversion service is not available!" This works fine with some other samples.

- [x] 3. Load any SBML sample and then export as "CellDesigner", we get "Conversion service is not available!" I thought we were using our own/native code for this conversion.

- [x] 4. Load PD sample "glycolysis" and export as "CellDesigner". Then import this file as "CellDesigner" and we get "Conversion service is not available!"

**Comment by umut-er** [comment]
I pushed the code to fix item number 1. That should be visible after rebuild. For items 2 and 4, I don't think there are easy fixes for those. The service we use returns an error with some files. I tried to debug that, but it's not clear what the issue is.

For item 3, we are not using our native code for that conversion. In fact, we are not using any code. We just assume the map is SBGN. For a temporary fix, we can convert SBML into SBGNML and then send that to the sbgnml2cd service. However, that would only keep visual information and completely disregard the simulation related information that we might implement. I think sbml to cd conversion might be an interesting project for the future.

**Comment by ugurdogrusoz** [comment]
for 2 and 4, we should display a warning saying "Conversion failed." rather than service is not available which is misleading.

for 3, we should treat this case as if the user wants to export to SBML since CD format is a valid SBML format (conversely, CD format is an extension of SBML format).

**Comment by umut-er** [comment]
This one is ready to review after rebuild.
