### ISSUE TITLE
Incorrect multimer complex rendering

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#76]
When a complex is marked as multimer, the paddings disappear and the label is drawn in the middle. 
No multimer:
![image](https://user-images.githubusercontent.com/3874988/27180249-373242c0-51db-11e7-8e25-9808f965e453.png)
Multimer:
![image](https://user-images.githubusercontent.com/3874988/27180259-47ce4b9c-51db-11e7-9952-95edbe2797d2.png)

**Comment by royludo** [comment]
I fixed this, and also issues with the textbox input when double clicking on it that wasn't placed correctly, and also the infoboxes that weren't refreshed correctly on resize. But I foresee many more issues through the code, in places where complexes are used. Due to the fact that 'complex' becomes a 'complex mutlimer'.
For example it's impossible to drag an element inside a multimer complex, either from the map or from the palette.

**Comment by ugurdogrusoz** [comment]
@royludo Basically what you're saying is we're breaking the rule about "not changing class for an object" here. Instead we should use the player-role design pattern for complexes. I'll open a separate issue for this.
